### ISSUE TITLE
Test on README does not pass (opaqueID is not valid)

### ISSUE THREAD

**Issue by aalises** [kiwicom/graphql-global-id#1]
The test on the README contains mocked information which would not pass and was a little bit misleading to me as I was trying to test some API calls with that ID which was not valid. Consider switching to a real passing test like: 
```js
it('returns correct original ID', () => {
  expect(fromGlobalId('TG9jYXRpb246bG9uZG9uX2di')).toBe('london_gb');
});
```

**Comment by michalsanger** [comment]
Fixed
